/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversorcentimetrospulgadas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class Conversorcentimetrospulgadas extends javax.swing.JFrame {

    /**
     * Creates new form Conversorcentimetrospulgadas
     */
    public Conversorcentimetrospulgadas() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        getContentPane().setBackground(Color.cyan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apulgadasButton = new javax.swing.JButton();
        acentimetrosButton = new javax.swing.JButton();
        centimetrosTextField = new javax.swing.JTextField();
        pulgadasTextField = new javax.swing.JTextField();
        centimetrosLabel = new javax.swing.JLabel();
        pulgadasLabel = new javax.swing.JLabel();
        conversorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de longitud");

        apulgadasButton.setBackground(new java.awt.Color(255, 204, 0));
        apulgadasButton.setText("A pulgadas");
        apulgadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apulgadasButtonActionPerformed(evt);
            }
        });

        acentimetrosButton.setBackground(new java.awt.Color(255, 204, 0));
        acentimetrosButton.setText("A centímetros");
        acentimetrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acentimetrosButtonActionPerformed(evt);
            }
        });

        centimetrosTextField.setBackground(new java.awt.Color(255, 204, 204));
        centimetrosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centimetrosTextFieldActionPerformed(evt);
            }
        });

        pulgadasTextField.setBackground(new java.awt.Color(255, 204, 204));
        pulgadasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulgadasTextFieldActionPerformed(evt);
            }
        });

        centimetrosLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        centimetrosLabel.setText("Centímetros");

        pulgadasLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pulgadasLabel.setText("Pulgadas");

        conversorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        conversorLabel.setText("CONVERSOR CENTÍMETROS - PULGADAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centimetrosLabel)
                    .addComponent(pulgadasLabel))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(centimetrosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(pulgadasTextField))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apulgadasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acentimetrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(conversorLabel)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(conversorLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apulgadasButton)
                    .addComponent(centimetrosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centimetrosLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acentimetrosButton)
                    .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulgadasLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centimetrosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centimetrosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centimetrosTextFieldActionPerformed

    private void pulgadasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulgadasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulgadasTextFieldActionPerformed

    private void apulgadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apulgadasButtonActionPerformed
        // TODO add your handling code here:
        String centimetrosString=centimetrosTextField.getText();
        if(centimetrosString.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Debe ingresar un número en el campo centímetros","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double centimetros;
        try
        {
            centimetros=Double.valueOf(centimetrosString);
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "El valor ingresado \""+centimetrosString+"\" no conforma un número", "ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        double pulgadas=centimetros/2.54;
        String pulgadasString=String.format("%.2f",pulgadas);
        pulgadasString=pulgadasString.replace(',','.');
        pulgadasTextField.setText(pulgadasString);
        
    }//GEN-LAST:event_apulgadasButtonActionPerformed

    private void acentimetrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acentimetrosButtonActionPerformed
        // TODO add your handling code here:
        String pulgadasString=pulgadasTextField.getText();
        if(pulgadasString.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Debe ingresar un número en el campo pulgadas","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double pulgadas;
        try
        {
            pulgadas=Double.valueOf(pulgadasString);
        }
        catch(NumberFormatException ex)
        {
             JOptionPane.showMessageDialog(this,"El valor ingresado \""+pulgadasString+"\" no conforma un número","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
        }
        double centimetros=pulgadas*2.54;
        String centimetrosString=String.format("%.2f",centimetros);
        centimetrosString=centimetrosString.replace(',','.');
        centimetrosTextField.setText(centimetrosString);
        
    }//GEN-LAST:event_acentimetrosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversorcentimetrospulgadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversorcentimetrospulgadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversorcentimetrospulgadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversorcentimetrospulgadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversorcentimetrospulgadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acentimetrosButton;
    private javax.swing.JButton apulgadasButton;
    private javax.swing.JLabel centimetrosLabel;
    private javax.swing.JTextField centimetrosTextField;
    private javax.swing.JLabel conversorLabel;
    private javax.swing.JLabel pulgadasLabel;
    private javax.swing.JTextField pulgadasTextField;
    // End of variables declaration//GEN-END:variables
}
